name: sip
description: "A secure Fintech project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Core Logic & Network
  dio: ^5.4.1
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.5.2
  package_info_plus: ^9.0.0 # Upgraded to fix dependency conflicts
  intl: ^0.19.0

  # Security & Identity
  flutter_secure_storage: ^9.0.0
  root_checker_plus: ^0.0.3
  device_info_plus: ^10.1.0
  screen_protector: ^1.5.1

  # UI & Design
  flutter_screenutil: ^5.8.4
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  carousel_slider: ^5.0.0
  pinput: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
